r"""Real-time propagators  v -> e^{-iHt} v  using only sparse mat-vecs.

Chebyshev engine (production; Tal-Ezer & Kosloff 1984).  With a bracket
[Emin, Emax] containing spec(H), a = (Emax-Emin)/2, b = (Emax+Emin)/2 and
Htil = (H-b)/a,

    e^{-iHt} = e^{-ibt} [ J_0(at) T_0(Htil) + 2 sum_{n>=1} (-i)^n J_n(at) T_n(Htil) ],

with T_n(Htil) v generated by the three-term recurrence.  The order N is sized from
the Bessel tail (|J_n(at)| <= tol for n > N).  For a fixed step dt the coefficients
are computed once and reused.  The bracket MUST contain the spectrum (underestimating
it makes the recurrence diverge); use ``sso.dqt.model.spectral_bracket``.

Krylov engine (alternative, ``engine="krylov"``): Arnoldi with full
re-orthogonalization, small exponential by scipy (CPU, double precision), long times
split into sub-steps with |dt| max|H_ij| <= 5.

Both engines run on numpy or cupy arrays (``usegpu``).
"""

import numpy as np
from scipy.linalg import expm as _dense_expm
from scipy.special import jv

from sso import backend

_NEGI_CYCLE = np.array([1.0, -1.0j, -1.0, 1.0j], dtype=np.complex128)   # (-i)^n exactly


def _required_order(alpha, tol):
    """Smallest N with |J_n(alpha)| <= tol for all n > N, plus 3 guard terms.

    The Bessel tail stays O(1) up to n ~ alpha and collapses over a window
    ~alpha^{1/3}, so N is read off the computed coefficients rather than a fixed buffer.
    """
    alpha = abs(float(alpha))
    nmax = int(np.ceil(alpha)) + max(40, int(10.0 * alpha ** (1.0 / 3.0)) + 40)
    sig = np.nonzero(np.abs(jv(np.arange(nmax + 1), alpha)) > tol)[0]
    return 1 if sig.size == 0 else max(1, int(sig[-1]) + 3)


def chebyshev_coeffs(t, Emin, Emax, N=None, tol=1e-14):
    """Coefficients c_n (n=0..N) of e^{-iHt} = sum_n c_n T_n(Htil) (numpy complex)."""
    a = 0.5 * (Emax - Emin)
    b = 0.5 * (Emax + Emin)
    if N is None:
        N = _required_order(a * t, tol)
    ns = np.arange(N + 1)
    c = jv(ns, a * t).astype(np.complex128)
    c[1:] *= 2.0
    c *= _NEGI_CYCLE[ns % 4]
    return c * np.exp(-1j * b * t)


def chebyshev_expm_multiply(H, v, t, Emin, Emax, coeffs=None, tol=1e-14, usegpu=False):
    """Return e^{-iHt} v by the Chebyshev expansion.

    ``H`` is a sparse/dense matrix with ``.dot`` or a callable matvec; ``coeffs`` (from
    :func:`chebyshev_coeffs`) overrides ``t`` and hoists the Bessel evaluation out of
    fixed-step loops.  Negative ``t`` gives backward evolution.
    """
    xp = backend.xp(usegpu)
    a = 0.5 * (Emax - Emin)
    b = 0.5 * (Emax + Emin)
    if coeffs is None:
        coeffs = chebyshev_coeffs(t, Emin, Emax, tol=tol)
    c = xp.asarray(coeffs)
    matvec = H.dot if hasattr(H, "dot") else H
    phi_prev = v.astype(xp.complex128)
    phi_cur = (matvec(phi_prev) - b * phi_prev) / a
    out = c[0] * phi_prev + c[1] * phi_cur
    for n in range(2, len(coeffs)):
        phi_next = 2.0 * ((matvec(phi_cur) - b * phi_cur) / a) - phi_prev
        out = out + c[n] * phi_next
        phi_prev, phi_cur = phi_cur, phi_next
    return out


def krylov_expm_multiply(A, v, t, m=50, tol=1e-12, usegpu=False):
    """exp(t A) v from an m-dimensional Arnoldi subspace (t may be complex, e.g. -1j*dt).

    Stops early on Krylov breakdown (h_{j+1,j} < tol).  The small m x m exponential is
    evaluated on the CPU by scipy (cupy's expm is less accurate).
    """
    xp = backend.xp(usegpu)
    n = A.shape[0]
    v = v.astype(xp.complex128)
    beta = float(xp.linalg.norm(v))
    if beta == 0:
        return v.copy()
    V = xp.zeros((n, m + 1), dtype=xp.complex128)
    Hm = np.zeros((m + 1, m), dtype=np.complex128)
    V[:, 0] = v / beta
    m_act = m
    for j in range(m):
        w = A.dot(V[:, j]) * t
        for i in range(j + 1):
            hij = complex(backend.to_cpu(xp.vdot(V[:, i], w)))
            Hm[i, j] = hij
            w = w - hij * V[:, i]
        Hm[j + 1, j] = float(xp.linalg.norm(w))
        if Hm[j + 1, j].real < tol:
            m_act = j + 1
            break
        V[:, j + 1] = w / Hm[j + 1, j].real
    y = _dense_expm(Hm[:m_act, :m_act])[:, 0] * beta
    return V[:, :m_act] @ xp.asarray(y)


def adaptive_krylov_expm_multiply(A, v, t, tol=1e-12, max_restarts=3, usegpu=False):
    """exp(t A) v, splitting t into sub-steps with |t_sub| max|A_ij| <= 5.

    Krylov dimension 50 (+20 per restart on failure) for dimension > 100
    (15/30 for tiny test matrices).
    """
    xp = backend.xp(usegpu)
    norm_est = float(backend.to_cpu(xp.max(xp.abs(A.data))))
    n_steps = max(1, int(np.ceil(abs(t) * norm_est / 5.0)))
    dt = t / n_steps
    n = A.shape[0]
    base, inc = (15, 10) if n <= 10 else (30, 15) if n <= 100 else (50, 20)
    step_tol = tol if n_steps == 1 else tol / 2
    out = v.copy()
    for _ in range(n_steps):
        for restart in range(max_restarts):
            try:
                out = krylov_expm_multiply(A, out, dt, m=base + restart * inc,
                                           tol=step_tol, usegpu=usegpu)
                break
            except Exception:
                if restart == max_restarts - 1:
                    raise
    return out


class Propagator:
    """Fixed-step propagator for e^{-iH dt} plus arbitrary-time evolution.

    ``engine="chebyshev"`` (production) precomputes the dt coefficients once;
    ``engine="krylov"`` uses :func:`adaptive_krylov_expm_multiply` with tol 1e-12.
    ``order`` is the Chebyshev order of one dt step (None for Krylov).
    """

    def __init__(self, H, dt, bracket, engine="chebyshev", usegpu=False):
        self.H, self.dt, self.usegpu = H, dt, usegpu
        self.Emin, self.Emax = bracket
        self.engine = engine.lower()
        if self.engine == "chebyshev":
            self._c = chebyshev_coeffs(dt, self.Emin, self.Emax)
            self.order = len(self._c) - 1
        elif self.engine == "krylov":
            self.order = None
        else:
            raise ValueError(f"unknown engine {engine!r}")

    def step(self, v):
        """e^{-iH dt} v."""
        if self.engine == "chebyshev":
            return chebyshev_expm_multiply(self.H, v, self.dt, self.Emin, self.Emax,
                                           coeffs=self._c, usegpu=self.usegpu)
        return adaptive_krylov_expm_multiply(self.H, v, -1j * self.dt, usegpu=self.usegpu)

    def evolve(self, v, t):
        """e^{-iH t} v for any real t."""
        if self.engine == "chebyshev":
            return chebyshev_expm_multiply(self.H, v, t, self.Emin, self.Emax, usegpu=self.usegpu)
        return adaptive_krylov_expm_multiply(self.H, v, -1j * t, usegpu=self.usegpu)
